// Utility script parsing and compiling fingerprinting manifest for bundle.
// Import rev manifest files generated by build script.
// Use non-fingerprinted file name if not successful.

try {
	let jsFp = require('./../../../public/assets/scripts/rev-manifest.json')
	jsFileName = jsFp['main']['js']
} catch(err) {
	console.log('Fingerprinted JavaScript bundle is not available. This is normal for development mode.')
	jsFileName = 'bundle.js'
}

/*
 * Delete GZip extension from the end of the filename.
 * @param {string} fileName
 * @returns {string} fileNameWithoutGzipExtension
 */
function deleteGzipExtension(fileName) {
	if (fileName == null) { return }
	if (fileName.slice(-3) === '.gz') {
		return fileName.slice(0, -3)
	}
	return fileName
}

// Delete Gzip extensions
var jsFileName = deleteGzipExtension(jsFileName)

export default {
	js:  jsFileName
}