// Utility script parsing and compiling fingerprinting manifests for scripts and styles.

var jsFileName, cssFileName

// Import rev manifest files generated by build script.
// Use non-fingerprinted file names if not successful.

// js
try {
	let jsFp = require('./../../../public/assets/scripts/rev-manifest.json')
	jsFileName = jsFp['bundle.js']
} catch(e) {
	jsFileName = 'bundle.js'
}

// css
try {
	cssFp = require('./../../../public/assets/styles/rev-manifest.json')
	cssFileName = cssFp['app.css']
} catch(e) {
	cssFileName = 'app.css'
}

// Delete GZip extension from the end of the filename.
function deleteGzipExtension(fileName) {
	if (fileName == null) { return }
	if (fileName.slice(-3) === '.gz') {
		return fileName.slice(0, -3)
	}
	return fileName
}

// Delete Gzip extensions
jsFileName = deleteGzipExtension(jsFileName)
cssFileName = deleteGzipExtension(cssFileName)

export default {
	js:  jsFileName,
	css: cssFileName
}