// Utility script parsing and compiling fingerprinting manifest for bundle.

var jsFileName

// Import rev manifest files generated by build script.
// Use non-fingerprinted file name if not successful.

// js
try {
	let jsFp = require('./../../../public/assets/scripts/rev-manifest.json')
	jsFileName = jsFp['main']['js']
} catch(err) {
	console.log(err)
	jsFileName = 'bundle.js'
}

// Delete GZip extension from the end of the filename.
function deleteGzipExtension(fileName) {
	if (fileName == null) { return }
	if (fileName.slice(-3) === '.gz') {
		return fileName.slice(0, -3)
	}
	return fileName
}

// Delete Gzip extensions
jsFileName = deleteGzipExtension(jsFileName)

export default {
	js:  jsFileName
}